### ISSUE TITLE
(Backend) Event model

### ISSUE THREAD

**Issue by joseph1wan** [gp-mn/inventory-trail#20]
# Backend ticket

**Story ticket**
- #13 
- #14 

**Use case**

Model in the database to represent a check in or check out event.

## Tech checklist
- [x] Requires changes to a model (and by default, a new migration)

## Requirements 

- [x] Create a new `Event` model

The model should have these fields:
- [x] item_group_id: integer (Django probably has a cleaner way to reference another model so may need to wait for `ItemGroup` to be done)
- [x] event_type: text
- [x] actor: string
- [x] datetime: datetime
- [x] num_items: integer (optional)

**Notes**

`num_items` helps count how many items have been checked out if relevant.

## Unit tests
**Create unit tests for each of these scenarios**

**Comment by AlienIdeology** [comment]
@joseph1wan hey I think I got confused on which ticket I was working on, and linked my branch to this ticket instead of #15. #15 is done, but this ticket should still be open as the feature isn't implemented yet.
