### ISSUE TITLE
(Backend) Generate slug based on item

### ISSUE THREAD

**Issue by joseph1wan** [gp-mn/inventory-trail#32]
# Backend ticket

**Story ticket**
- #

**Use case**

Each item should have a unique identifier (slug) that can be used in routing and in QR code generation.

## Tech checklist
- [ ] Requires changes to a model (and by default, a new migration)

## Dependencies

- #15 

## Requirements 

@baeleb , you had an idea about hashing or making this more secure. Can you fill out some requirements details?

**Notes**

## Unit tests
**Create unit tests for each of these scenarios**

**Comment by joseph1wan** [comment]
> @joseph1wan For clarification, we are generating a slug for each item group, right?
> Do we want the slug to be based on the name of the item, or an ID, or a combination of both? Is this up to Caleb and I to figure out?

Yes, a slug for each item group. So you'd want to add a method to the `ItemGroup` model. It's up to you and Caleb to figure out how you want to generate the slug.

**Comment by AlienIdeology** [comment]
@joseph1wan do we want to allow multiple item groups with the same name+location? if we don't, we will want to do some sort of verification before item groups are created, and this would affect slug behavior (as it's probably best to do the lookup for duplicated items using the slug). 
I'm pushing some changes rn that work well if we allow duplicated item groups. It autogenerates the slugs. The slugs aren't based on names or location so if we do a lookup we will have to look up by name and location, which would be slower than looking up by the slug.
Also, an important note, we added a dependency: https://github.com/nshafer/django-hashid-field

**Comment by AlienIdeology** [comment]
@joseph1wan can I get some feedback on this ^
thanks!

**Comment by joseph1wan** [comment]
We don't want to allow duplicate item groups. If people really need to keep track of multiple sets, they should name it "Volleyball 1", etc.

Agreed we want to do lookup by slug. We should save the slug in the database to help with faster lookup

No problem with adding dependencies.
