### ISSUE TITLE
Onboarding tasks for David

### ISSUE THREAD

**Issue by davidburchell** [gp-mn/inventory-trail#6]
# Onboarding
Welcome to the GP MN Inventory Trail project. To get access

**Logistical Tasks**
- [x] Ask @joseph1wan for access to collaboration tools (Slack, Google Sheets).
- [x] Join our Slack channel and say `hello` in #admin.
- [x] Fill out your skill level in the Roster tab.
- [x] Look at the **Important dates** tab and fill out expected absences if you have any.
- [x] Decide a weekly pair-programming time that works for you and your mentor/mentee.

**Technical Tasks**
- [x] Get familiar with Django: [Django overview video](https://www.youtube.com/watch?v=0sMtoedWaf0)
- [x] Take an introductory course (4 hours) on Django if you aren't at least familiar with it: [Django course)](https://www.udemy.com/course/try-django-2-2-python-web-development/?ranMID=39197&ranEAID=JVFxdTr9V80&ranSiteID=JVFxdTr9V80-M2IaeWc_xBVIq2fYIu0y4A&LSNPUBID=JVFxdTr9V80&utm_source=aff-campaign&utm_medium=udemyads)
- [x] Ask for your first issue

If at any time you have questions, ask in the #help-onboarding channel in Slack.

**Comment by jedichang99** [comment]
Good job finishing onboarding. Now you need to ask Josaph for your first ticket.
